### ISSUE TITLE
gem version 0.4.4.4 is not published for ruby platform

### ISSUE THREAD

**Issue by elik-ru** [blackwinter/unicode#9]
I want to force version 0.4.4.4 in my Gemfile, because version 0.4.4.2 does not build unicode_native.so for ruby 2.3. But there is no 0.4.4.4 version for ruby platform (linux/macos):

41 VERSIONS SINCE AUGUST 12, 2005:
0.4.4.4 - February 7, 2013 x86-mingw32 (2.06 MB)
0.4.4.4 - February 7, 2013 x86-mswin32-60 (2.06 MB)
0.4.4.3 - February 7, 2013 x86-mswin32-60 (1.59 MB)
0.4.4.3 - February 7, 2013 x86-mingw32 (1.59 MB)
0.4.4.2 - February 7, 2013 (125 KB)
0.4.4.2 - February 7, 2013 x86-mingw32 (1.15 MB)
0.4.4.2 - February 7, 2013 java (11 KB)
0.4.4.2 - February 7, 2013 x86-mswin32-60 (1.15 MB)

So if i lock version to 0.4.4.4 it works on window, but can't be found in linux/macos.

Can you please publish it ?
Or advise another way to fix this problem ?

**Comment by blackwinter** [comment]
I pushed the Ruby and Java gems for [0.4.4.4](https://rubygems.org/gems/unicode/versions/0.4.4.4).
